// <auto-generated />
using System;
using CW10___Kolokwium.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CW10___Kolokwium.Migrations
{
    [DbContext(typeof(TestDbContext))]
    [Migration("20210511212737_newInitial")]
    partial class newInitial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CW10___Kolokwium.Models.Championship", b =>
                {
                    b.Property<int>("idChampionship")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("OfficialName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("idChampionship");

                    b.ToTable("Championships");

                    b.HasData(
                        new
                        {
                            idChampionship = 1,
                            OfficialName = "euro2016",
                            Year = 2016
                        },
                        new
                        {
                            idChampionship = 2,
                            OfficialName = "mundial",
                            Year = 2012
                        },
                        new
                        {
                            idChampionship = 3,
                            OfficialName = "euro2012",
                            Year = 2012
                        });
                });

            modelBuilder.Entity("CW10___Kolokwium.Models.Championship_Team", b =>
                {
                    b.Property<int>("idChampionshipTeam")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<float>("Score")
                        .HasColumnType("real");

                    b.Property<int>("idChampionship")
                        .HasColumnType("int");

                    b.Property<int>("idTeam")
                        .HasColumnType("int");

                    b.HasKey("idChampionshipTeam");

                    b.HasIndex("idChampionship");

                    b.HasIndex("idTeam");

                    b.ToTable("championship_Teams");

                    b.HasData(
                        new
                        {
                            idChampionshipTeam = 1,
                            Score = 1f,
                            idChampionship = 1,
                            idTeam = 1
                        },
                        new
                        {
                            idChampionshipTeam = 2,
                            Score = 2f,
                            idChampionship = 1,
                            idTeam = 2
                        },
                        new
                        {
                            idChampionshipTeam = 3,
                            Score = 3f,
                            idChampionship = 3,
                            idTeam = 1
                        });
                });

            modelBuilder.Entity("CW10___Kolokwium.Models.Player", b =>
                {
                    b.Property<int>("IdPlayer")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdPlayer");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            IdPlayer = 1,
                            DateOfBirth = new DateTime(1997, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Josef",
                            LastName = "Zbaznik"
                        },
                        new
                        {
                            IdPlayer = 2,
                            DateOfBirth = new DateTime(1999, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Pawlo",
                            LastName = "Karsik"
                        },
                        new
                        {
                            IdPlayer = 3,
                            DateOfBirth = new DateTime(2007, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Hadol",
                            LastName = "Ajtler"
                        });
                });

            modelBuilder.Entity("CW10___Kolokwium.Models.PlayerTeam", b =>
                {
                    b.Property<int>("idPlayerTeam")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Comment")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("NumOnShirt")
                        .HasColumnType("int");

                    b.Property<int>("idPlayer")
                        .HasColumnType("int");

                    b.Property<int>("idTeam")
                        .HasColumnType("int");

                    b.HasKey("idPlayerTeam");

                    b.HasIndex("idPlayer");

                    b.HasIndex("idTeam");

                    b.ToTable("PlayerTeams");

                    b.HasData(
                        new
                        {
                            idPlayerTeam = 1,
                            NumOnShirt = 0,
                            idPlayer = 1,
                            idTeam = 1
                        },
                        new
                        {
                            idPlayerTeam = 2,
                            NumOnShirt = 0,
                            idPlayer = 2,
                            idTeam = 1
                        },
                        new
                        {
                            idPlayerTeam = 3,
                            NumOnShirt = 0,
                            idPlayer = 3,
                            idTeam = 1
                        });
                });

            modelBuilder.Entity("CW10___Kolokwium.Models.Team", b =>
                {
                    b.Property<int>("idTeam")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MaxAge")
                        .HasColumnType("int");

                    b.Property<string>("TeamName")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("idTeam");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            idTeam = 1,
                            MaxAge = 18,
                            TeamName = "Legia"
                        },
                        new
                        {
                            idTeam = 2,
                            MaxAge = 20,
                            TeamName = "Lech"
                        },
                        new
                        {
                            idTeam = 3,
                            MaxAge = 16,
                            TeamName = "Wisła"
                        });
                });

            modelBuilder.Entity("CW10___Kolokwium.Models.Championship_Team", b =>
                {
                    b.HasOne("CW10___Kolokwium.Models.Championship", "Championship")
                        .WithMany("Championship_Teams")
                        .HasForeignKey("idChampionship")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CW10___Kolokwium.Models.Team", "Team")
                        .WithMany("Championship_Teams")
                        .HasForeignKey("idTeam")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Championship");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("CW10___Kolokwium.Models.PlayerTeam", b =>
                {
                    b.HasOne("CW10___Kolokwium.Models.Player", "Player")
                        .WithMany("PlayerTeams")
                        .HasForeignKey("idPlayer")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CW10___Kolokwium.Models.Team", "Team")
                        .WithMany("PlayerTeams")
                        .HasForeignKey("idTeam")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("CW10___Kolokwium.Models.Championship", b =>
                {
                    b.Navigation("Championship_Teams");
                });

            modelBuilder.Entity("CW10___Kolokwium.Models.Player", b =>
                {
                    b.Navigation("PlayerTeams");
                });

            modelBuilder.Entity("CW10___Kolokwium.Models.Team", b =>
                {
                    b.Navigation("Championship_Teams");

                    b.Navigation("PlayerTeams");
                });
#pragma warning restore 612, 618
        }
    }
}
