// <auto-generated />
using System;
using CW_12.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CW_12.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20210616182102_elo")]
    partial class elo
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CW_12.Models.Student", b =>
                {
                    b.Property<int>("idStudent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Avatar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Studies")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("idStudent");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            idStudent = 1,
                            Avatar = "https://cdn.icon-icons.com/icons2/2643/PNG/512/male_boy_person_people_avatar_icon_159358.png",
                            BirthDate = new DateTime(2000, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Adam",
                            LastName = "Banan",
                            Studies = "Informatyka"
                        },
                        new
                        {
                            idStudent = 2,
                            Avatar = "https://cdn.icon-icons.com/icons2/2643/PNG/512/male_boy_person_people_avatar_icon_159358.png",
                            BirthDate = new DateTime(2001, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Paweł",
                            LastName = "Czerniak",
                            Studies = "Informatyka"
                        },
                        new
                        {
                            idStudent = 3,
                            Avatar = "https://image.flaticon.com/icons/png/512/194/194938.png",
                            BirthDate = new DateTime(2002, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Natalia",
                            LastName = "Zachaj",
                            Studies = "Kulturoznawsto"
                        },
                        new
                        {
                            idStudent = 4,
                            Avatar = "https://cdn.icon-icons.com/icons2/2643/PNG/512/male_boy_person_people_avatar_icon_159358.png",
                            BirthDate = new DateTime(2001, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Rudolf",
                            LastName = "Stronheim",
                            Studies = "Germanistyka"
                        },
                        new
                        {
                            idStudent = 5,
                            Avatar = "https://image.flaticon.com/icons/png/512/194/194938.png",
                            BirthDate = new DateTime(2004, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Monika",
                            LastName = "Kurczyk",
                            Studies = "Kulturoznawsto"
                        },
                        new
                        {
                            idStudent = 6,
                            Avatar = "https://cdn.icon-icons.com/icons2/2643/PNG/512/male_boy_person_people_avatar_icon_159358.png",
                            BirthDate = new DateTime(2002, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Michał",
                            LastName = "Parchaś",
                            Studies = "Kulturoznawsto"
                        },
                        new
                        {
                            idStudent = 7,
                            Avatar = "https://cdn.icon-icons.com/icons2/2643/PNG/512/male_boy_person_people_avatar_icon_159358.png",
                            BirthDate = new DateTime(2002, 7, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Michał",
                            LastName = "Zachajewczyk",
                            Studies = "Obrona narodowa"
                        },
                        new
                        {
                            idStudent = 8,
                            Avatar = "https://cdn.icon-icons.com/icons2/2643/PNG/512/male_boy_person_people_avatar_icon_159358.png",
                            BirthDate = new DateTime(1998, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Tytus",
                            LastName = "Bomba",
                            Studies = "Obrona narodowa"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
