// <auto-generated />
using System;
using CW_14.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CW_14.Migrations
{
    [DbContext(typeof(MyDbContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CW_14.Models.Action", b =>
                {
                    b.Property<int>("IdAction")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("NeedSpecialEquipment")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("IdAction");

                    b.ToTable("Actions");

                    b.HasData(
                        new
                        {
                            IdAction = 1,
                            EndDate = new DateTime(2020, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NeedSpecialEquipment = true,
                            StartDate = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            IdAction = 2,
                            EndDate = new DateTime(2021, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NeedSpecialEquipment = false,
                            StartDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            IdAction = 3,
                            EndDate = new DateTime(2019, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NeedSpecialEquipment = true,
                            StartDate = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("CW_14.Models.FireTruck", b =>
                {
                    b.Property<int>("IdFireTruck")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("OperationalNumber")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("SpecialEquipment")
                        .HasColumnType("bit");

                    b.HasKey("IdFireTruck");

                    b.ToTable("FireTrucks");

                    b.HasData(
                        new
                        {
                            IdFireTruck = 1,
                            OperationalNumber = "213545f",
                            SpecialEquipment = true
                        },
                        new
                        {
                            IdFireTruck = 2,
                            OperationalNumber = "POLONIA",
                            SpecialEquipment = true
                        },
                        new
                        {
                            IdFireTruck = 3,
                            OperationalNumber = "LGBTNKWD",
                            SpecialEquipment = false
                        });
                });

            modelBuilder.Entity("CW_14.Models.FireTruck_Action", b =>
                {
                    b.Property<int>("IdFireTruck_Action")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AssigmentTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdAction")
                        .HasColumnType("int");

                    b.Property<int>("IdFireTruck")
                        .HasColumnType("int");

                    b.HasKey("IdFireTruck_Action");

                    b.HasIndex("IdAction");

                    b.HasIndex("IdFireTruck");

                    b.ToTable("FireTruck_Actions");

                    b.HasData(
                        new
                        {
                            IdFireTruck_Action = 1,
                            AssigmentTime = new DateTime(2021, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdAction = 1,
                            IdFireTruck = 1
                        },
                        new
                        {
                            IdFireTruck_Action = 2,
                            AssigmentTime = new DateTime(2021, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdAction = 2,
                            IdFireTruck = 1
                        },
                        new
                        {
                            IdFireTruck_Action = 3,
                            AssigmentTime = new DateTime(2021, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdAction = 1,
                            IdFireTruck = 3
                        });
                });

            modelBuilder.Entity("CW_14.Models.Firefighter", b =>
                {
                    b.Property<int>("IdFirefigther")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdFirefigther");

                    b.ToTable("Firefighters");

                    b.HasData(
                        new
                        {
                            IdFirefigther = 1,
                            FirstName = "John",
                            LastName = "Doe"
                        },
                        new
                        {
                            IdFirefigther = 2,
                            FirstName = "Greg",
                            LastName = "Hans"
                        },
                        new
                        {
                            IdFirefigther = 3,
                            FirstName = "Joe",
                            LastName = "Zonk"
                        });
                });

            modelBuilder.Entity("CW_14.Models.Firefighter_Action", b =>
                {
                    b.Property<int>("IdFirefighter")
                        .HasColumnType("int");

                    b.Property<int>("IdAction")
                        .HasColumnType("int");

                    b.HasKey("IdFirefighter");

                    b.HasIndex("IdAction");

                    b.ToTable("Firefighter_Actions");

                    b.HasData(
                        new
                        {
                            IdFirefighter = 1,
                            IdAction = 1
                        },
                        new
                        {
                            IdFirefighter = 2,
                            IdAction = 2
                        },
                        new
                        {
                            IdFirefighter = 3,
                            IdAction = 3
                        });
                });

            modelBuilder.Entity("CW_14.Models.FireTruck_Action", b =>
                {
                    b.HasOne("CW_14.Models.Action", "Action")
                        .WithMany("FireTruck_Actions")
                        .HasForeignKey("IdAction")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CW_14.Models.FireTruck", "FireTruck")
                        .WithMany("FireTruck_Actions")
                        .HasForeignKey("IdFireTruck")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Action");

                    b.Navigation("FireTruck");
                });

            modelBuilder.Entity("CW_14.Models.Firefighter_Action", b =>
                {
                    b.HasOne("CW_14.Models.Action", "Action")
                        .WithMany("Firefighter_Actions")
                        .HasForeignKey("IdAction")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CW_14.Models.Firefighter", "Firefighter")
                        .WithMany("Firefighter_Actions")
                        .HasForeignKey("IdFirefighter")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Action");

                    b.Navigation("Firefighter");
                });

            modelBuilder.Entity("CW_14.Models.Action", b =>
                {
                    b.Navigation("Firefighter_Actions");

                    b.Navigation("FireTruck_Actions");
                });

            modelBuilder.Entity("CW_14.Models.FireTruck", b =>
                {
                    b.Navigation("FireTruck_Actions");
                });

            modelBuilder.Entity("CW_14.Models.Firefighter", b =>
                {
                    b.Navigation("Firefighter_Actions");
                });
#pragma warning restore 612, 618
        }
    }
}
